### ISSUE TITLE
Search Parameter on URL

### ISSUE THREAD

**Issue by esridoyle** [Esri/local-government-online-apps#11]
Hi
Is there a way to specify the search parameter on the URL such that the application searches for e.g. a PARCELID on startup? I've been looking but can seem to find.

Thanks

Eamonn

**Comment by busbus** [comment]
Mike - we had another request for this from St Tammany Parish, they wanted the pass the parcel number into the URL so that they could link to it from their parcel search on the website.

**Comment by sirws** [comment]
+1

**Comment by sirws** [comment]
http://ideas.arcgis.com/ideaView?id=087E00000005IDRIA2

**Comment by busbus** [comment]
Scott - we're looking into it.  Can the client use the parcel viewer?  The parcel viewer has this functionality - http://tryitlive.arcgis.com/TaxParcelViewer/?parcelId=0714213001

**Comment by sirws** [comment]
Just to give this a little bump... this sort of search has been added to the Basic Viewer template in the latest release.  Would be GREAT to have in the FINDER app...

![l_4dc0 tmp](https://cloud.githubusercontent.com/assets/793576/8731732/18f6c6a0-2bae-11e5-94c0-11a2fa76a806.PNG)

**Comment by MikeTschudi** [comment]
Added to 'develop' branch via commit 37cc9f0e749c5f1195a73adb253b7830d3df2344

**Comment by allisonmuise** [comment]
Verified that URL parameters based on the search fields work in devext. This enhancement will be included in the next release of ArcGIS Online.
cc: @esridoyle , @sirws
