### ISSUE TITLE
Integrate with Network Analyst?

### ISSUE THREAD

**Issue by sernstGIS** [Esri/local-government-online-apps#12]
Is there any way you could create a driving directions/routing panel for Finder?  It'd be nice to let users get directions to the item they searched for.

I know this is a little complex, since right now the networking on ArcGIS Online is all from the ESRI network analysis data - and that's by user login only.  Ideally, I'd like to be able to use my own network analysis data so I can push this out to citizens.

**Comment by allisonmuise** [comment]
Check out the new Directions template for this functionality
http://www.arcgis.com/home/item.html?id=556db83093934365a8d7e2f294aa785b

**Comment by sernstGIS** [comment]
That’s exciting!  Thank you- I’ll check it out right now.

Shawna Ernst – GIS Senior Analyst – 509.477.7531
Spokane County, Washington

Did you find an address or street that is incorrect?  Send the details to:
PublicSafetyGIS@spokanecounty.org<mailto:PublicSafetyGIS@spokanecounty.org>
