### ISSUE TITLE
Pop-up not centered in map on a mobile device

### ISSUE THREAD

**Issue by karmstro77** [Esri/local-government-online-apps#18]
When opening the finder app on an iPhone 5, after selecting an item in the search results, the map is zoomed to the item and its pop-up window is opened. However, half of the pop-up is off the screen.

![img_1584](https://cloud.githubusercontent.com/assets/6819070/4631062/aa2f3a5a-53b2-11e4-876d-487de6e74869.PNG)

**Comment by allisonmuise** [comment]
This is a known issue. The map centers the feature and the popup is displayed to the side of the issue. We don't have any plans to change this in the app at this time.

**Comment by karmstro77** [comment]
Why are there no plans to change this? It will be difficult to get users to implement this if the pop-ups dont work properly?
