### ISSUE TITLE
how to modify template to show popup for selected addresses

### ISSUE THREAD

**Issue by jgravois** [Esri/local-government-online-apps#24]
a customer asked me today whether (in Find), after [configuring the app](http://solutions.arcgis.com/state-government/help/finder/get-started/additional-configuration/#locator-search) to utilize World Geocoding Service, it is possible to display a popup for matched/selected addresses.

i spent some time trying to digest the logic of the application, but i can't quite pin how we go from the object which includes a label [here](https://github.com/Esri/local-government-online-apps/blob/master/js2/lgonlineCommand.js#L2619https://github.com/Esri/local-government-online-apps/blob/master/js2/lgonlineCommand.js#L2619) to a raw Point geometry [here](https://github.com/Esri/local-government-online-apps/blob/master/js2/lgonlineMap.js#L303).

**Comment by allisonmuise** [comment]
The application won’t display a popup for a geocoded result because it does not associate address locations with nearby features. The popup is only displayed for feature results.

**Comment by jgravois** [comment]
i'm aware that the template doesn't already accomplish this out of the box, but it would be fairly trivial to inject an infoTemplate when the graphic is created (using the attributes returned by the World Geocoding Service) if we could figure out why by the time we pass the result [here](https://github.com/Esri/local-government-online-apps/blob/master/js2/lgonlineDrawing.js#L90) they have already been stripped out.
