### ISSUE TITLE
Finder url in the readme file is broken

### ISSUE THREAD

**Issue by Smallmelo** [Esri/local-government-online-apps#27]
The url for the text, 'Want more info on Finder? Check out the documentation.'  is broken.

Current url:
http://solutionsdev.arcgis.com/local-government/help/finder/

Is this the url you are meaning to point to?
http://solutions.arcgis.com/local-government/help/finder/

**Comment by allisonmuise** [comment]
thanks! Fixed in the develop branch. This change will appear in the master branch readme after the next release (early july)
