### ISSUE TITLE
unclear directions in readme.md 

### ISSUE THREAD

**Issue by Smallmelo** [Esri/local-government-online-apps#28]
Directions on deploying your own version of the app beyond step 5 are unclear.  Suggestion: add a 6th step: Follow directions for "Defining the Find Layers and Fields value and the Result Display Layers and Fields value" on the additional configuration page (http://solutions.arcgis.com/local-government/help/finder/get-started/additional-configuration)

**Comment by allisonmuise** [comment]
updated on the develop branch. This will get moved to production with the next release in July.
