### ISSUE TITLE
Features templates enabled for features layers whose add/delete capability is disabled

### ISSUE THREAD

**Issue by Smallmelo** [Esri/local-government-online-apps#30]
I filed the bug with Joshua at Esri tech support. He took screenshots, etc. Case #01663572.  Please keep me posted.

Feature services published using 10.2.2

**Comment by allisonmuise** [comment]
Please track this issue through the customer care portal. That will have more up-to-date information than this issue..

**Comment by mlundeen** [comment]
This issue appears to have been incorrectly translated into the wrong defect.  I am able to reproduce this today.  If the editable feature layer has its Create Feature operation disabled, it works properly in the webmap viewer (not allowing the user to see/select a feature template nor draw any new feature on the map).  However, in the Find, Edit & Filter app, the feature template selector appears and the user may choose a template and begin drawing on the map even though feature creation has been disabled in the layer (Editors can only update feature attributes.) Any new features they are created appear to be actually saved.

**Comment by allisonmuise** [comment]
@mlundeen : Thanks for clarifying this. It does appear that the feature creation issue was what was reported in the original incident, although that's not what was reported through devtopia. I'll re-open the related devtopia issue with this new info, and we'll take a look for a future release.
