### ISSUE TITLE
Error in "Add legend Widget" Instructions

### ISSUE THREAD

**Issue by Smallmelo** [Esri/local-government-online-apps#32]
The iconUrl should point to "images/legend32.png" - lower case L, not upper case in these <a href="http://solutions.arcgis.com/state-government/help/finder/get-started/additional-configuration/#legend">instructions</a>.  

Some browsers can't handle casing inconsistencies.

**Comment by allisonmuise** [comment]
fixed in the next release of the Solutions site.
Thanks!
