### ISSUE TITLE
Support for Vector tiles

### ISSUE THREAD

**Issue by allisonmuise** [Esri/local-government-online-apps#37]
Vector tile basemaps do not display in the basemap widget

**Comment by MikeTschudi** [comment]
Basemap widget appears to have been fixed:
![image](https://cloud.githubusercontent.com/assets/2125181/11819709/2b71b846-a316-11e5-86ba-717254f85df2.png)

This gallery is using the configuration
```
"basemapBox.basemapgroupTitle": "Vector Basemaps (Beta)",
"basemapBox.basemapgroupOwner": "esri",
```

**Comment by MikeTschudi** [comment]
Known limitations with vector tiles (may affect their display in the basemap widget):
* "May only be displayed in Internet Explorer 11 and higher and other current versions of desktop browsers, including Chrome, Firefox, and Safari. Edge is not supported at this time."
* "Tiles are sometimes not renderered [sic] in the map viewer (Chrome) - known limitation with graphic cards."
